export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REGISTERING_USER = 'REGISTERING_USER';
export const LOGGING_IN_USER = 'LOGGING_IN_USER';

export const FETCHING_TWEETS = 'FETCHING_TWEETS';
export const FETCH_TWEETS_ERROR = 'FETCH_TWEETS_ERROR';
export const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS';

export const CREATING_LEAGUE = 'CREATING_LEAGUE';
export const CREATE_LEAGUE_SUCCESS = 'CREATE_LEAGUE_SUCCESS';
export const FETCHING_LEAGUES = 'FETCHING_LEAGUES';
export const FETCH_LEAGUES_ERROR = 'FETCH_LEAGUES_ERROR';
export const FETCH_LEAGUES_SUCCESS = 'FETCH_LEAGUES_SUCCESS';
