export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REGISTERING_USER = 'REGISTERING_USER';
export const LOGGING_IN_USER = 'LOGGING_IN_USER';

// export const FETCHING_TWEETS = 'FETCHING_TWEETS';
// export const FETCH_TWEETS_ERROR = 'FETCH_TWEETS_ERROR';
// export const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS';

export const FETCHING_LEAGUES = 'FETCHING_LEAGUES';
export const FETCH_LEAGUES_ERROR = 'FETCH_LEAGUES_ERROR';
export const FETCH_LEAGUES_SUCCESS = 'FETCH_LEAGUES_SUCCESS';

export const FETCHING_LEAGUE = 'FETCHING_LEAGUE';
export const FETCH_LEAGUE_ERROR = 'FETCH_LEAGUE_ERROR';
export const FETCH_LEAGUE_SUCCESS = 'FETCH_LEAGUE_SUCCESS';

export const FETCHING_TEAMS = 'FETCHING_TEAMS';
export const FETCH_TEAMS_ERROR = 'FETCH_TEAMS_ERROR';
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
export const FETCHING_TEAM = 'FETCHING_TEAM';
export const FETCH_TEAM_ERROR = 'FETCH_TEAM_ERROR';
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS';

export const ADD_FAVORITE_TEAM = 'ADD_FAVORITE_TEAM';
export const REMOVE_FAVORITE_TEAM = 'REMOVE_FAVORITE_TEAM';

export const ADD_BOOKMARKED_ITEM = 'ADD_BOOKMARKED_ITEM';
export const REMOVE_BOOKMARKED_ITEM = 'REMOVE_BOOKMARKED_ITEM';
